### ISSUE TITLE
Required Development

### ISSUE THREAD

**Issue by b-irb** [kukrimate/mfgd#2]
List of requirements for collaborators:
- [x] Implement `/` endpoint to select a repository for navigation.
- [x] Implement `/login` endpoint to authenticate with a registered user account.
- [x] Implement `/register` endpoint to create user account.
- [x] Implement `/profile` endpoint to view and modify profile attributes.
- [x] Implement visibility to require authentication to view private repositories.
- [x] Implement visibility to require authentication to manage repositories.
- [x] Implement `/<repo>/chain` endpoint for inspecting commit log with optional commit offset.
- [x] Implement `/<repo>/info` endpoint for inspecting commit itself (timestamp, author, message).
- [x] Implement patch viewer in `/<repo>/info` endpoint for deltas in specified commit.
- [x] Implement `/<repo>/tree` endpoint for inspecting the tree at a specific commit or branch.
- [x] Allow users to inspect blobs and associated commits from `/<repo>/tree` view.
- [x] Allow users to view textual blobs with syntax highlighting.
- [x] Allow users to view binary blobs with hex dump.
- [x] Allow users to view most recent commit in `/<tree>/tree/path/to/file` affecting `path/to/file`.
- [x] Implement `/<repo>/manage` to modify repository visibility and user permissions.
- [x] Implement navigation bar for logouts, logins, registrations, and shortcuts to endpoints (`/info`, `/chain`, etc.).
- [ ] Implement clean looking error handlers for 4xx and 5xx HTTP status codes.
- [ ] Implement `/<repo>/collaborator/<email>` endpoint for inspecting collaborator contributions. (?)
- [x] Implement `/manage` endpoint to add repository from web view. (?)

Additional changes pertain to improving the templates aesthetically (there are certain issues with media queries breaking pages and misaligned `<table>`'s).

**Comment by kukrimate** [comment]
The new design is basically complete, so not many aesthetic improvements are necessary. There are some minor bugs to fix.

**Comment by kukrimate** [comment]
Did you do the HTTP handlers? If yes I will tick that. And the collaborator thing should probably be removed from the list, there is just not enough time.

**Comment by b-irb** [comment]
I was planning to do more fanciful 404 and 5xx error pages but Django does not return the proper HTTP status codes with the `Http404`/`Http500` routines - though the pages themselves render. I might remove them at some point because right now they serve no purpose, there are instances where plain-text is returned to the user (grep for `return HttpResponseNotFound`). The collaborator page should be removed because you're right that we have no more time. Otherwise, the consolidation of repository management needs to happen then we are, for the most part, done. (see #5 for additional work required).
